### ISSUE TITLE
List Customers by Email

### ISSUE THREAD

**Issue by kirstenspiteri** [securionpay/securionpay-net#17]
Can you please add the following two lines in SecurionPay\Request\CustomerListRequest.cs ?

`[JsonProperty("email")]`
`public string Email { get; set; }`

This will add the functionality to List Customers by Email. I tried to do it myself but couldn't create a pull request due to error 403.

**Comment by SecurionPay-Team** [comment]
We've released a fix for this in 2.3.2. Thank you for reporting the issue!

**Comment by kirstenspiteri** [comment]
Thanks
